sudo: false
language: node_js
services:
node_js:
  - 0.10
  - 4.2
  - 5
before_script:
  - npm install -g grunt-cli
  - npm install -d
branches:
  only:
    - master
script:
  - npm test
after_success:
  - codeclimate < ./coverage/lcov.info
addons:
  apt:
    packages:
      - libzmq3-dev
  code_climate:
    repo_token:
      secure: KEzF7HrYPGv7oRQvUOBMFLy8VpNok1l4Bssg1PdDMEScMvcQ9uClWss0KOUq0gi9HzgtLVOFcOIsKjq1pxopF5qSOOfzrSqnxW6oXRQrRu+mGGDMrIZR6eT1HK3cUNfR5rIhSMrF2bQOQCus2eg0i43Q0VmJbDZBXFgJHKwUzwY=
